# Generated by Django 5.1.6 on 2025-05-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programcategory',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
