# Generated by Django 5.1.6 on 2025-05-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_program_options_alter_program_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='programcategory',
            options={'ordering': ['name'], 'verbose_name': 'Program Category', 'verbose_name_plural': 'Program Categories'},
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in months'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name', 'category'], name='Chat_progra_name_fca0da_idx'),
        ),
    ]
