# Generated by Django 5.1.6 on 2025-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_program_options_alter_programcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcategory',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in months'),
        ),
    ]
